/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.11-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package edu.odds.api;

import edu.odds.model.Bet;
import edu.odds.model.Odds;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-12-18T10:06:35.423+02:00")

@Api(value = "odds", description = "the odds API")
@RequestMapping(value = "")
public interface OddsApi {

    @ApiOperation(value = "Find Odds by Bet ID", nickname = "oddsBetIdGet", notes = "Returns a list of odds for a given bet ID", response = Bet.class, tags = {"odds",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Odds are returned for bet ID", response = Bet.class),
            @ApiResponse(code = 400, message = "Invalid Bet ID supplied"),
            @ApiResponse(code = 404, message = "Bet not found for given ID")})
    @RequestMapping(value = "/odds/{betId}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<Bet> oddsBetIdGet(@ApiParam(value = "ID of bet to return", required = true) @PathVariable("betId") Long betId);


    @ApiOperation(value = "Offer odds for a bet", nickname = "oddsPost", notes = "", tags = {"odds",})
    @ApiResponses(value = {
            @ApiResponse(code = 201, message = "Odds have been created for bet"),
            @ApiResponse(code = 400, message = "Invalid format of Odds")})
    @RequestMapping(value = "/odds",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> oddsPost(@ApiParam(value = "Odds that should be offered for a bet", required = true) @Valid @RequestBody Odds body);

}
